name: Unit tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Go test
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'path/to/go.mod'
          check-latest: true
          cache: true
      - run: go run hello.go
